{% set name = "ads-async" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 0abf1cce1ec89d3cab9ab9ca48a0dac0f997d7b73832fc33f5d839f0899f35b5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - ads_async

about:
  home: https://github.com/pcdshub/ads-async
  doc_url: https://pcdshub.github.io/ads-async
  dev_url: https://github.com/pcdshub/ads-async
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE
  summary: Sans-I/O and asyncio TwinCAT3 ADS testing server in pure Python.

extra:
  recipe-maintainers:
    - klauer
    - zllentz
    - zrylettc
